baseURL = "https://Eddie023.github.io/"
languageCode = "en-us"
title = "Brain Dumps"
theme = 'hugo-theme-cactus'

[params]
colortheme = "white"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[params.social]]
  name = "github"
  link = "https://github.com/Eddie023"

[[params.social]]
  name = "email"
  link = "manish23chaulagain@gmail.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/manish-chaulagain-35430b136/"
